// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMnbvqjR0Mce7_G9aUQrRK5sirU9XFfQY',
    appId: '1:892501981139:web:834daf7743963494bfa126',
    messagingSenderId: '892501981139',
    projectId: 'split-e7887',
    authDomain: 'split-e7887.firebaseapp.com',
    storageBucket: 'split-e7887.appspot.com',
    measurementId: 'G-L2ECRYFFS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxA-UnLxU4WlNAQTKELavtmVUvfoLPr_w',
    appId: '1:892501981139:android:5a3c91fbac8e87b0bfa126',
    messagingSenderId: '892501981139',
    projectId: 'split-e7887',
    storageBucket: 'split-e7887.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEBbPlVFh8nHsruf4A6lwaEhgqeH7vhWM',
    appId: '1:892501981139:ios:4a1ab016d2ed18b9bfa126',
    messagingSenderId: '892501981139',
    projectId: 'split-e7887',
    storageBucket: 'split-e7887.appspot.com',
    iosClientId: '892501981139-hk40u9e6tumetva8mjgmo82rjhgpa6ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.split',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEBbPlVFh8nHsruf4A6lwaEhgqeH7vhWM',
    appId: '1:892501981139:ios:df2ec3d4f6211743bfa126',
    messagingSenderId: '892501981139',
    projectId: 'split-e7887',
    storageBucket: 'split-e7887.appspot.com',
    iosClientId: '892501981139-tb1bv8po1gojlq6vfoad9ljk8m2j14d7.apps.googleusercontent.com',
    iosBundleId: 'com.split.app',
  );
}
